Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Variaveis
// Autor(a)    : Henrique Cruz
// Data atual  : 16/09/2021
Var
// Seção de Declarações das variáveis 
//priemiro nome
//segundo nome
//idade
//cidade
//endereço

          primeiroNome, segundoNome, cidade, endereco: caractere
          idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 



Fimalgoritmo